name: doc2vec
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - faiss-gpu=1.8.0
  - mecab=0.996
  - cudatoolkit=11.8
  - pytorch=2.4.1
  - torchvision
  - torchaudio
  - transformers=4.45.1
  - tiktoken=0.7.0
  - tqdm=4.66.5
  - pillow=10.4.0
  - protobuf=5.28.2
  - python-dateutil=2.9.0.post0
  - pytz=2024.2
  - pyyaml=6.0.2
  - tokenizers=0.20.0
  - triton=3.0.0
  - typing-extensions=4.12.2
  - tzdata=2024.2
  - pip:
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - elastic-transport==8.15.0
      - elasticsearch==8.15.1
      - filelock==3.16.1
      - fsspec==2024.9.0
      - gensim==4.3.3
      - huggingface-hub==0.25.1
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - jpype1==1.5.0
      - konlpy==0.6.0
      - lxml==5.3.0
      - markupsafe==2.1.5
      - mecab-python3==1.0.9
      - mpmath==1.3.0
      - networkx==3.3
      - python-dotenv==1.0.1
      - regex==2024.9.11
      - requests==2.32.3
      - safetensors==0.4.5
      - six==1.16.0
      - smart-open==7.0.4
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - wrapt==1.16.0
